### PR TITLE
Voltamon

### PR DESCRIPTION
**Pull request by Voltamon**
I have added the try : except block inside the for loop. You can check it out. I have run it personally to check if it works. It works smooth as butter and congratulations !! your program is unbreakable now

### CODE REVIEW

**Comment by swarnali13** [comment]
Hello! I checked your code and I'm find with it. Could you please explain the logic of try and raise function?

**Comment by swarnali13** [comment]
Hey I noticed one thing which  for which i made a change. Over the code block except you had given the display message as 'please enter a valid choice' but as i had already given it in the portion of (a/b/c/d/e/f/g) preference for operation, it is therefore confusing for the user to understand. So i replaced it with 'please enter a valid value' thus it will be easy for the user to understand. Thank you for your suggestions tho. I really liked them!

**Comment by Voltamon** [comment]
> Hello! I checked your code and I'm find with it. Could you please explain the logic of try and raise function?

Yes sure, in due course of a program, we often encounter various kind of exceptions, the cases we didn't expect to happen, and it eventually breaks the program. We use the try : except block to handle those exceptions

For example, in your program, the try block contains many conversion of user input to float. What if the user gives an alphanumeric input, the interpreter will not be able to convert it into float and hence, it will raise ValueError, in order to handle that, I have used the except block to guide the program what to d, if such an error occurs instead of breaking the program completely

**Comment by Voltamon** [comment]
> Hey I noticed one thing which for which i made a change. Over the code block except you had given the display message as 'please enter a valid choice' but as i had already given it in the portion of (a/b/c/d/e/f/g) preference for operation, it is therefore confusing for the user to understand. So i replaced it with 'please enter a valid value' thus it will be easy for the user to understand. Thank you for your suggestions tho. I really liked them!

That's a great idea, Awesome project overall

**Pull request merged**
